CREATE TABLE product_option_types
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL,

    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);


CREATE TABLE product_option_values
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_type_id BIGINT       NOT NULL,
    value          VARCHAR(100) NOT NULL,

    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     TIMESTAMP,

    CONSTRAINT fk_option_values_option
        FOREIGN KEY (option_type_id) REFERENCES product_option_types (id) ON DELETE CASCADE
);

CREATE TABLE product_options
(
    product_id     uuid   NOT NULL,
    option_type_id BIGINT NOT NULL,
    PRIMARY KEY (product_id, option_type_id),
    CONSTRAINT fk_po_product FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT fk_po_option FOREIGN KEY (option_type_id) REFERENCES product_option_types (id) ON DELETE CASCADE
);

CREATE TABLE product_variants
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id     uuid                NOT NULL,
    sku            VARCHAR(100) UNIQUE NULL,
    price          DECIMAL(12, 2)      NOT NULL,
    stock_quantity INT                 NOT NULL DEFAULT 0,
    created_at     TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP           NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at     TIMESTAMP,

    CONSTRAINT fk_variant_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE
);

CREATE TABLE product_variant_option_values
(
    variant_id      BIGINT NOT NULL,
    option_value_id BIGINT NOT NULL,
    PRIMARY KEY (variant_id, option_value_id),
    CONSTRAINT fk_map_variant
        FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE,
    CONSTRAINT fk_map_option_value
        FOREIGN KEY (option_value_id) REFERENCES product_option_values (id) ON DELETE CASCADE
);

ALTER TABLE product_images
    ADD COLUMN variant_id BIGINT NULL;

ALTER TABLE product_images
    ADD CONSTRAINT fk_image_variant FOREIGN KEY (variant_id) REFERENCES product_variants (id) ON DELETE CASCADE;
